### ISSUE TITLE
sharp:make:list command make filter

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#155] opened 2019-07-29 10:00 UTC
Hello,

The artisan command ```php artisan sharp:make:list <class_name>``` is creating an EntityListFilter instead of a SharpEntityList.

My Sharp version is : 4.1.16

**Comment by dvlpp** [comment] 2019-07-30 09:37
😬
This feature is NOT tested, and was added by a PR that I merged maybe too quickly...
Please feel free to fix this in a PR; if not, I'll do it, but maybe in a while, since it's not a core feature.

**Comment by dvlpp** [comment] 2019-08-22 09:25
I finally take a look, and this is in fact... not a bug. `php artisan sharp:make:list <class_name>` does not exist, but `artisan` guess you meant `php artisan sharp:make:list-filter <class_name>`. To create an Entity List, the command is `php artisan sharp:make:entity-list <class_name>`

**Closed by dvlpp** 2019-08-22 09:25 UTC
Labels: invalid

**Comment by jefffairson** [comment] 2019-08-26 08:21
OK, thanks for the info, I did'nt check in the source codes (lack of time I Guess)
But just for info, there is a mistake in the documentation on this page :
https://sharp.code16.fr/docs/guide/building-entity-list.html#generator
