### ISSUE TITLE
SharpFormWysiwygField doesn't work in command form

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#159] opened 2019-08-02 13:20 UTC
Nothing is displayed when adding a Wysiwyg field to a command form. Markdown fields seem to work just fine.

```php
    function buildFormFields()
    {
        // ...

        $this->addField(
            SharpFormWysiwygField::make("body")
                ->setLabel("Message")
                ->setHeight(200)
                ->setToolbar([
                    SharpFormWysiwygField::B,
                    SharpFormWysiwygField::I,
                    SharpFormWysiwygField::A,
                    SharpFormWysiwygField::SEPARATOR,
                    SharpFormWysiwygField::UL,
                    SharpFormWysiwygField::OL,
                    SharpFormWysiwygField::SEPARATOR,
                    SharpFormWysiwygField::CODE,
                    SharpFormWysiwygField::QUOTE,
                    SharpFormWysiwygField::SEPARATOR,
                    SharpFormWysiwygField::UNDO,
                    SharpFormWysiwygField::REDO,
                ])
        );
    }
```

![Screenshot_2019-08-02 SOMA Site, Users Sharp 4 1 16](https://user-images.githubusercontent.com/1303475/62372916-f2558e00-b538-11e9-9631-02745d730ed5.png)

**Comment by dvlpp** [comment] 2019-08-12 10:07
Confirmed bug, will fix.

**Comment by dvlpp** [comment] 2019-08-28 13:24
Mmm, after re-check, I'm not able to reproduce this one. Can you confirm this issue, and share the whole Command code?

**Comment by dvlpp** [comment] 2019-09-08 09:15
Hi @nsrosenqvist, I'm going to close this issue since I wasn't able to reproduce it (see previous comment). Please provide a full example (with your Sharp version number) if you are still experiencing this, I'll re-open it if necessary.

**Closed by dvlpp** 2019-09-08 09:15 UTC
Labels: bug

**Comment by nsrosenqvist** [comment] 2019-09-08 13:53
Hi @dvlpp, sorry I didn't respond sooner. I don't have time to investigate this further, hopefully some change in master has already taken care of it!
