### ISSUE TITLE
Entity List: how to add multiple delete action (checkboxes)

### ISSUE THREAD

**Issue by falconeri** [code16/sharp#115] opened 2019-04-05 16:52 UTC
Is there any guide how to add multiple checkboxes when build Entity list, so we can tick all checkboxes then do delete action?

**Comment by dvlpp** [comment] 2019-04-06 07:00
That’s not possible for now. Solution may be to filter data with a dedicated filter and to apply an entity command on the results

**Comment by dvlpp** [comment] 2019-04-15 09:36
(closing this since it's not a bug)

**Closed by dvlpp** 2019-04-15 09:36 UTC
Labels: wontfix
