### ISSUE TITLE
Support for adding and removing related items

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#153] opened 2019-07-25 13:57 UTC
Hey, thanks for open sourcing Sharp! I'm trying to figure out how to work with models that have hasMany relationships. I'm trying to create a screen for managing roles and users assigned to those roles but I can't figure out how something like that would best be accomplished and not shoehorn the framework to do something it can't.

I have `spatie/laravel-permissions` installed and I'm trying to list all permissions and make them selectable, using a list or autocomplete field for this would be a nightmare, so I've listed all permissions but can't map them as existing or not. Ive tried solving this with a transform in `find` but it feels very hacky and doesn't show as toggled on the screen.

```php
        $this->setCustomTransformer('permissions', function($rolePermissions) {
            $permissions = array_column(Permission::all()->toArray(), 'name');
            $permissions = array_fill_keys($permissions, false);
            
            foreach ($rolePermissions as $permission) {
                $permissions[$permission['name']] = true;
            }

            return $permissions;
        });
```

![Screenshot_2019-07-25 Handball sample, Roles Sharp 4 1 16(1)](https://user-images.githubusercontent.com/1303475/61879182-dd527c80-aef2-11e9-918b-818eed83ab3a.png)

For the second tab I've chosen to implement it with a list and autocomplete field but can't get it to display properly either, but I think that might be an error on my part somewhere.

To me it seems like there is no planned means of working with this kind of relationship which isn't about changing a value but adding or removing items. Am I completely blind reading the documentation or is there no way of working with data set up with this kind of relationships?

**Comment by dvlpp** [comment] 2019-07-26 08:10
First, if the relationship is a `belongsToMany` (I think you have a pivot table in your case, between `users` and `permissions`, but I'm not familiar with Spatie's package), you can use a `SharpFormSelectField` with `->setDisplayAsList()` to show a checklist, like in the "Features" example in Saturn, Sharp's companion project:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/973325/61936021-1ab71880-af8c-11e9-8426-7820370bbc92.png">

https://github.com/code16/sharp/blob/master/saturn/app/Sharp/SpaceshipSharpForm.php

If your case is more complex, you'll have more code to write in the `find()` and `update()` methods. I saw you tried to do that, but I'll need to whole code to figure out why the checkboxes are not valued — could be in the way they are defined.

**Comment by nsrosenqvist** [comment] 2019-07-27 17:20
Ok, I think I've figured out what I did wrong. However I think I've discovered a couple of bugs unless it's just me misunderstanding how the classes are meant to be used again.

1. When I set `setInline` on `SharpFormSelectField` they don't show up inline, they only get added padding in a vertical list.
2. `SharpFormAutocompleteField` doesn't work with a collection of models in `setLocalValues`  (as stated in the documentation) but must have them converted to an array first.
3. `SharpFormAutocompleteField` only compares with start of string and one can't filter email by domain for example ("@example.com").
4. Even though I set `ignore` on fields in the update method (in my use case "users" and "permissions" as I'm creating a permission editing screen) they still get updated automatically when I call `save` on the instance.

Is there any way of making commands executable from an instance screen? I find it really inconvenient not being able to for example change a password from within the instance screen or send an email to the user (as examples). Having to go out to the list view seems really counter-intuitive. Am I missing something here as well?

A feature request I have would be to be able to add an item to a list by opening a modal with a form rather than first creating an item and then filling it out, so that it could be added to a list of read-only items.

If these are in fact bugs I'll create separate issues for them (and close this issue) but I thought it best to just continue the conversation here to not create unnecessary noise in the bug tracker.

**Comment by dvlpp** [comment] 2019-07-28 12:56
Well:

- please fill bugs for each one of your 4 points, we can look into it more precisely. I think (from where I am) that 1 is a regression, 2 may need further investigation, 3 is not a bug (but maybe a cool feature to add, see #110), and 4 is really odd since we use this feature a lot.
- you **can't** call an instance command from the form, and that's part of Sharp's "concept": form is a transient state, data shown may not reflect persisted data (and may not be valid at all). So instance commands are callable from list only, and from a future show view (hopefully we'll look into this feature in the coming month—I wrote a [small spec here](https://github.com/code16/sharp/wiki/Sharp-show-view:-specification-draft) on this topic).
- But you can create an instance command [with a custom form](https://sharp.code16.fr/docs/guide/commands.html#write-the-command-class), and you are free to do whatever you want in the command execution code, like create a new instance. I've done it in the past for a read only list (especially powerful with custom command permissions). 
Note that to see the new instance added to the list, you'll need to return a `reload` action in your command code.

I'm closing this issue because I think there is no bug here, but please fill issues for your 4 possible bugs, and feel free to continue the conversation here, on the closed issue.

**Closed by dvlpp** 2019-07-28 12:56 UTC

**Comment by nsrosenqvist** [comment] 2019-07-28 21:49
@dvlpp I read the draft on the Show view and that would be a great fit for showing instance commands. Many times one would have to preview the data (more than what a table can present) before determining if a command should be run, and then having to return to the list view and relocate the correct instance would be very counterintuitive. I'd gladly welcome that feature. I'll add the commands as regular instance commands for the time being and await news regarding the Show feature.

I'll test 1 and 2 a bit more to figure out the behavior and perhaps file separate issues for the two. Thanks again!

**Comment by nsrosenqvist** [comment] 2019-07-29 09:44
Ok, after some investigation...

1. It seems like the class "SharpSelect__item--inline" should have `float: left`, filed a new issue: https://github.com/code16/sharp/issues/154
2. I was mistaken, the `SharpFormAutocompleteField` documentation specifically states that `setLocalValues` requires an object array. However, the tutorial blog post (https://medium.com/code16/about-sharp-for-laravel-part-2-9c7779782f31) shows `all` being called directly on the model (`Team::all()`) while it doesn't work for me without first converting it to an array: `Users::all()->toArray()`. Is that intentional or is that a regression?
3. https://github.com/code16/sharp/issues/110
4. Not a bug as I described it. I believe the instance is updated with the data when calling `$this->ignore('permissions')->save($instance, $data)` but the property is excluded from the database update. So the model instance is changed and doesn't reflect its saved state, and I continued doing work with the instance, expecting the property to not have been altered on the model instance at all since `ignore` is called prior to `save($instance, $data)`. Not sure if this is the expected behavior.

Please advise on if 2 and 4 are unexpected behaviors and should be filed as bugs.

**Comment by dvlpp** [comment] 2019-07-30 09:36
Mmm, I think 2 is a regression. Please fill a bug for this, I'll look into it.
For the 4, I'm not sure to fully understand the case. Could you please share the full `save()` code?

**Comment by nsrosenqvist** [comment] 2019-07-31 09:11
@dvlpp nevermind 4, I debugged the issue and noticed that it was an error totally on my part.
