### ISSUE TITLE
Data disappear when submitted form

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#228] opened 2020-02-04 22:14 UTC
Hello,

I have a really strange behaviour, before all I am on Laravel 5.8.36 and sharp 4.2.2
For the following form, everything is fine at display. If I submit the form without selecting a picture I've got the correct value ind data (which is null anyway) but when I select a pic and submit the form data is then empty... by digging in the sharp form class I found that the issue seems to appear in the `formatRequestData` method, everything is ok in input but nothing in output.

My models are a bit tricky with many relationships, maybe it's because of that, anyway I'm stuck...

This is the form :
```<?php

namespace App\Sharp;

use App\Models\Page;
use App\Models\PageBlock;
use App\Enums\PageBlocksTypes;
use Code16\Sharp\Form\SharpForm;
use Code16\Sharp\Http\WithSharpContext;
use Code16\Sharp\Form\Layout\FormLayoutColumn;
use Code16\Sharp\Form\Fields\SharpFormTextField;
use Code16\Sharp\Form\Fields\SharpFormUploadField;
use Code16\Sharp\Form\Fields\SharpFormMarkdownField;
use App\Models\PageBlocks\PageBlocksTextBlueRoundedTop;
use Code16\Sharp\Form\Eloquent\WithSharpFormEloquentUpdater;

class BlockTextBlueRoundedTopSharpForm extends SharpForm
{
    use WithSharpFormEloquentUpdater, WithSharpContext;
    
    /**
     * Retrieve a Model for the form and pack all its data as JSON.
     *
     * @param $id
     * @return array
     */
    public function find($id): array
    {
        return $this
                ->setCustomTransformer("blockable[topstamp]",
                    new FormUploadModelTransformer()
                )
                ->transform(
                    PageBlock::with('blockable', 'blockable[topstamp]')->findOrFail($id)
                );
    }

    /**
     * @param $id
     * @param array $data
     * @return mixed the instance id
     */
    public function update($id, array $data)
    {
        dd($data);
        
        /// save stuff
        
        return $pageBlock->id;
    }

    /**
     * @param $id
     */
    public function delete($id)
    {
        //
    }

    /**
     * Build form fields using ->addField()
     *
     * @return void
     */
    public function buildFormFields()
    {
        $this
            ->addField(
                SharpFormUploadField::make("topstamp")
                            ->setLabel("Tampon au dessus")
                            ->setStorageDisk("public")
                            ->setStorageBasePath("blocks/Stamps/{id}")
            );
    }

    /**
     * Build form layout using ->addTab() or ->addColumn()
     *
     * @return void
     */
    public function buildFormLayout()
    {
        $this->addColumn(12, function(FormLayoutColumn $column) {
            $column
                ->withSingleField('topstamp');
        });
    }
}
```

**Comment by dvlpp** [comment] 2020-02-05 07:40
Could you post the code of your `PageBlock` Model + the result of your `dd()`? And ideally, also post the original payload of the POST request (from your browser console, like Chrome dev tool "Headers" tab)

**Comment by jefffairson** [comment] 2020-02-05 08:10
Hi, this is the page block model : 
```<?php

namespace App\Models;

use App\Models\Page;
use Illuminate\Database\Eloquent\Model;

class PageBlock extends Model
{
    protected $fillable = [
        'name', 'page_id', 'blockable_type', 'blockable_id', 'display'
    ];

    public function blockable()
    {
        return $this->morphTo();
    }

    public function page()
    {
        return $this->belongsTo(Page::class);
    }
}
```
The dd is just an empty array `[]`

And the screen shot.

![Screenshot 2020-02-05 at 09 09 39](https://user-images.githubusercontent.com/25099423/73822845-55312600-47f7-11ea-8fde-65e0dae2c333.png)

**Comment by dvlpp** [comment] 2020-02-05 08:26
Mmm, `topstamp` is NOT an attribute of `PageBlock`, so it is striped by Sharp. I think, from what I see, it would work with some adjusts (not tested...):

```php
    public function find($id): array
    {
        return $this
                ->setCustomTransformer("blockable:topstamp",
                    new FormUploadModelTransformer()
                )
                ->transform(
                    PageBlock::with('blockable', 'blockable.topstamp')->findOrFail($id)
                );
    }

    public function buildFormFields()
    {
        $this
            ->addField(
                SharpFormUploadField::make("blockable:topstamp")
                            ->setLabel("Tampon au dessus")
                            ->setStorageDisk("public")
                            ->setStorageBasePath("blocks/Stamps/{id}")
            );
    }

    public function buildFormLayout()
    {
        $this->addColumn(12, function(FormLayoutColumn $column) {
            $column->withSingleField('blockable:topstamp');
        });
    }
```

See https://sharp.code16.fr/docs/guide/how-to-transform-data.html#the-separator-and-transformers

**Comment by jefffairson** [comment] 2020-02-05 08:31
It's actually an attribute of a relation for more consistency (the PageBlock is just a placeholder, the data of the blocks are stored in the blockable relationship).
But if it's not possible that way, I will set it as an attribute of the PageBlock model.

**Comment by dvlpp** [comment] 2020-02-05 08:34
OK, I let you test that — but notice that if `topstamp` is an attribute of the `blocktable` relation, my code proposal would work. I close this issue since it's not a bug, as it seems, but feel free to keep posting here if needed.

**Closed by dvlpp** 2020-02-05 08:34 UTC

**Comment by jefffairson** [comment] 2020-02-05 08:35
Ok, I will test that and keep you inform, thank for your help.

**Comment by jefffairson** [comment] 2020-02-05 08:41
I tried quickly and I've got the exact same behavior.
I just forgot to precise something, as pageblocks are included in pages, I build a page show (which is a great feature by the way) and blocks are created from this page show.

**Comment by jefffairson** [comment] 2020-02-11 17:21
I finally take the issue the other and it work perfectly now with a more efficient result ! ;)

**Comment by ZuzanaBasovska** [comment] 2020-02-19 11:03
I have exactly the same problem, could you please specify, how did you solve it?
