### ISSUE TITLE
Relationship Problems ?

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#233] opened 2020-02-17 22:29 UTC
Hello,
I'm stuck for a few days with an error saying ```Undefined index: xxx``` with a field name associated to a relation ship.
I was trying to understand what happened with the Saturn example, but when I tried to fill a spaceship I had exactly the same issue (cf. screenshot), is there an issue when saving the relationships ?

![Screenshot 2020-02-17 at 23 25 55](https://user-images.githubusercontent.com/25099423/74689903-3fe7ce80-51dd-11ea-85f5-7392cc6541d5.png)

**Comment by dvlpp** [comment] 2020-02-19 09:26
I'm guessing you are in a creation case? For relationship involving a foreign key in the related table, Sharp will call `update()` on your Form twice: one without theses relations, and one only for them, because we need an `id` on the created model to handle them.

On Saturn the issue is here: https://github.com/code16/sharp/blob/871bcb1475bfb8241d1654d0962a391febea61fd/saturn/app/Sharp/SpaceshipSharpForm.php#L298

As you can see a few line up, for the `name` attribute, we have a `isset` check, but it's missing for `capacity`, and that's the problem: as this is a creation, Sharp do the update in two parts and on the second one `capacity` is not set. CustomTransformers will handle this gently, but with a direct access to the array, we HAVE TO perform an `isset` check first. 

Please look if this is your situation, and if so close this issue. I will add a note on this in the documentation (and fix Saturn...)

**Comment by jefffairson** [comment] 2020-02-19 09:38
Hello,
Thanks for the reply, it was actually a value in a transformer which was not existing in creation.

Just a quick complement question, what happen to the ```data``` array after invoking the ```save``` function ?

I have a similar issue with this updater :
```
$pageBlock = $id ? PageBlock::findOrFail($id) : null;
        
        $pageBlocksTeamMember = $pageBlock ? PageBlocksTeamMember::with('member_photo')->findOrFail($pageBlock->blockable_id) : new PageBlocksTeamMember;

        if(!$this->context()->isCreation()) {
            $pageBlocksTeamMember->pageblock()->update([
                'name' => $data['name']
            ]);
        }
        
        $this
            ->ignore([
                'name'
            ])
            ->save($pageBlocksTeamMember, $data);
        
        if($this->context()->isCreation()) {
            if($breadcrumb = $this->context()->getPreviousPageFromBreadcrumb("show")) {
                    list($type, $entityKey, $instanceId) = $breadcrumb;
                    $pb = PageBlock::create([
                        'name' => $data['name'],
                        'page_id' => $instanceId,
                        'blockable_type' => PageBlocksTypes::TEAMMEMBER(),
                        'blockable_id' => $pageBlocksTeamMember->id
                    ]);
                }
        }

        return  $id ?? $pb->id;
```
In this case, at creation, "name" was undefined, is the ```ignore``` function get rid of the data array ?

**Closed** 2020-02-19 09:38 UTC

**Comment by dvlpp** [comment] 2020-03-04 14:19
Just added a section in the documentation on this issue: https://sharp.code16.fr/docs/guide/form-fields/upload.html#delayed-creation. I must add here that I was imprecise: this delayed creation case leading to a double call to `update()` only occurs on a creation of a Model with a filled upload for which storage path is configured with an `{id}` placeholder.
